### ISSUE TITLE
Sort View on Blog Entry

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.contenttypes.blog#1]
Eine extra Browser View auf dem Contenttype Blog Entry die das ortieren der beinhalteten Dateien und Bilder ermöglicht.

Diese soll dann als Modal-Dialog in der Edit-Form aufgerufen werden können.

**Comment by reinhardt** [comment]
Grundsätzliche Implementation ist fertig. Ich habe versucht, die Sort-View mit data-reveal-id und data-reveal-ajax als Modal auf gehen zu lassen, aber das hat nicht geklappt. Ich habe einen Verdunklungs-Effekt gesehen, aber es ist kein Modal aufgetaucht. Wenn ich eine existierende ID in data-reveal-id angebe, dann wird mir der Inhalt in die offene Seite hinein gerendert anstatt in ein Modal. Hast Du damit Erfahrung?

**Comment by loechel** [comment]
Klären wir beim Gespräch,
Foundation hat kein Injection Pattern

**Comment by reinhardt** [comment]
data-reveal-ajax soll angeblich etwas ähnliches tun. Ich könnte stattdessen aber auch die Overlay-Tools von Plone benutzen.

**Comment by reinhardt** [comment]
Notiz an mich: Aktuellen Stand schon mal nach edit-form mergen

**Comment by reinhardt** [comment]
> Notiz an mich: Aktuellen Stand schon mal nach edit-form mergen

Done!

**Comment by loechel** [comment]
the view itself looks good, but isn't a submit and cancle button missing and necessary?

Haven't llok on modal, but if necessary we could go by prepoverlay

**Comment by reinhardt** [comment]
> but isn't a submit and cancle button missing and necessary?

No, like in the folder contents, a position change is saved instantly.

**Comment by reinhardt** [comment]
Ich schließe das Ticket mal, ich arbeite ja eh schon in #19 weiter.
