### ISSUE TITLE
Image Cropping (04a_crop)

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.contenttypes.blog#10]
Es soll für die Bilder in den Blog Einträgen eine Cropping Funktionalität geben.

Die Cropping View von plone.app.imagecropping ist aber nicht das was wir wollen.

Ziel ist es batchmäßig alle Scales auf einmal zuzuschneiden, mit einem Radio Button Selector für Freies Seitenverhältnis oder Fixes definiertes Seitenverhältnis (16x9, siehe teaser Formate), Es soll jeweils zu den Buttons eine kurzer Erklärungstext erscheinen:
- "festes Seitenverhältnis (optimiert für Darstellungen auf Übersichtsseiten)"
- "freies Seitenverhältnis"

Die Button Beschriftung:
- Cropping Info Speichern: "Bildzuschnitt speichern"
- Löschen der Cropping Information: "Zurücksetzen zum Originalbild" .

**Comment by reinhardt** [comment]
Im branch [easy-cropping](https://github.com/loechel/lmu.contenttypes.blog/tree/easy-cropping) ist eine erste Implementation des Batch-Croppings, und zwar ist es so gedacht, dass man alle Teaser-Scales (und sonst keine) in den Cropping-Einstellungen unter "Bildgrößen für Cropping Editor" auswählt. Der Cropping-Editor skaliert diese dann alle auf einmal. (Die Thumb-Scale kann dabei nicht mit skaliert werden, weil sie ja ein anderes Seitenverhältnis hat.)

Zum freien Seitenverhältnis: Wie genau ist das gedacht? Man kann ja keine Scales mit freiem Verhältnis definieren. Sollen hier die tatsächlichen Bilddaten ersetzt werden? Das könnte aufwendiger werden, weil das in p.a.imagecropping so nicht vorgesehen ist.

**Comment by reinhardt** [comment]
P.S. es ist noch kein Link zum Cropping-Editor drin, man muss von Hand /@@croppingeditor an die URL anhängen.

**Comment by reinhardt** [comment]
Nochmal zur Kontrolle, ob ich's richtig verstanden habe:

Das Umschalten zwischen festem und freiem Seitenverhältnis ist nur eine Hilfe für den Benutzer. Der gewählte Ausschnitt, egal mit welchem Seitenverhältnis, wird als Basis für _alle_ Scales verwendet. Wenn nötig wird der gewählte Bildausschnitt erweitert, damit er auf die Scale passt.

Zur Sicherheit vielleicht noch ein Beispiel. Sagen wir, ich habe dieses Originalbild:

![image_full](https://cloud.githubusercontent.com/assets/202439/10199497/dce0042a-6798-11e5-8da2-083a1c92c704.jpg)

Dann wähle ich als Bildausschnitt die beiden Personen, also einen Hochkant-Ausschnitt:

![image_portrait](https://cloud.githubusercontent.com/assets/202439/10199516/f3ea3b0e-6798-11e5-9df2-31001b2a917f.jpg)

Für die Querformat-Scales wird links und rechts wieder etwas dazu genommen (so dass ich in diesem Fall beinahe wieder das Originalbild habe):

![image_landscape](https://cloud.githubusercontent.com/assets/202439/10199553/272acca4-6799-11e5-9ae8-6d06d15c6755.jpg)

Dieses Seitenverhältnis sehe ich dann an den meisten Stellen, z.B. als Teaser und in der Popup-Gallerie.

Gleiches Vorgehen aber leicht anderes Ergebnis bei den quadratischen Scales:

![image_square](https://cloud.githubusercontent.com/assets/202439/10199596/616b39d0-6799-11e5-80d9-58e1c72139f7.jpg)

Das sehe ich z.B. als Thumbs auf der Standardansicht des Blogeintrags.

Es könnte für den Benutzer allerdings unverständlich sein, dass er einen Hochkant-Ausschnitt auswählen kann, den dann aber nirgends zu Gesicht bekommt. Ich meine auch, dass Du zwischendurch sagtest, dass man den unangepassten Bildausschnitt in der Popup-Gallerie sehen soll. Das würde allerdings mit den Scales nicht funktionieren. Hab ich noch irgendwo einen Denkfehler drin?

**Comment by loechel** [comment]
erstmal Danke Manuel, das du es so genau beschreibst, und beispiel Bilder machst.
Ich sehe einen das ein aspekt nicht richtig verstanden wurde. Ich werde morgen mit einem Kollegen auf Basis deiner Beispielbilder genauer kommentieren und erwünschte Ausgabe für verschiedene Sacles und Directions visualisieren.

Bis dahin bitte erstmal and der Thematik pausieren. ggf. die Sort thematik #19 ansehen.

**Comment by loechel** [comment]
Ok Manuel,

wir haben selber lange intern diskutiert und versucht zu klären wie es denn nun sein soll. 

Dabei bin ich auch auf Plone Interna eingegangen und habe versucht das verständnis zu finden warum es so schwer zu erklären ist. 

Das folgende Bild sollte schematisch erklären was los ist.
<img width="1024" alt="lmu - 22" src="https://cloud.githubusercontent.com/assets/1766708/10220740/e5cf3144-6849-11e5-9725-d01d5c3bf07a.png">

Plone speicht ja interen via plone.namedfile die Bilder als orginal ab.
Plone.app.imagecropping füght hier einen layer hinzu, der virtuell das orginal Bild ersetzt für jeden Scale. Dieser Scale wird dann nach den Regeln von plone.scale behandelt.

Bilder werden via https://github.com/plone/plone.scale/blob/master/plone/scale/scale.py#L69 gescalet, hier gibt es drei directions: up, down und thumbnail, auch wenn plone.scale als default down verwendet, überschriebt plone.named file das mit thumbnail.

Wir verwenden aber explizit direction down für die listing_thumbs und *_teaser formate. Somit kommt auf das Scaling auf dem gecroppten Bild ein zusätzliches autocropping wie im Bild dargestellt.
Wenn jetzt ein exacter Bildausschnitt in dem Seitenverhältnis der Teaser ausgewählt wird, ist das autocropping == dem Scale/manuell Crop.

Ich hoffe jetzt wird es verständlich.

Also, was wollen wir.
Die Nutzer sollen einen beliebigen Bildausschnitt des Original Bildes auswählen können.
Ich fände es gut wenn man alle drei resultierenden Ergebnisbilder darstellen könnte, so das er sieht was man bekommt, aber das ist kür.
Wichtig ist, dass alle Scales auf einmal zugeschnitten werden.

Wenn du Fragen hast melde dich bitte.

Kurioserweise ist die Doku hier nicht richtig.
