### ISSUE TITLE
sort views

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.contenttypes.blog#19]
- file-Buttons anpassen
- drag and drop
- modal prüfen
- Reihenfolge (reverse order)

**Comment by reinhardt** [comment]
> - Reihenfolge (reverse order)

Ich denke, ich weiß, was hier passiert ist. Ich hatte ursprünglich die Bilder und Dateien in umgekehrter Ordnerreihenfolge angezeigt, damit ein neu hoch geladenes Bild immer ganz oben erscheint. Dann wurde diese Darstellung von Dir (oder jemand anderem) um geschrieben, so dass sie die normale Ordnerreihenfolge benutzt. Meine Sortier-View benutzt aber immer noch die alte umgekehrte Reihenfolge.

Inzwischen wird ja das erste Bild gesondert behandelt, insofern ist es nicht mehr sinnvoll, dass das zuletzt hoch geladene Bild oben einsortiert wird. Ich werde also die Reihenfolge in der Sortier-View angleichen.

**Comment by reinhardt** [comment]
Notiz an mich:
- "Fertig" Button
- gezielten Reload wieder herstellen

**Comment by reinhardt** [comment]
Bis auf Drag&Drop ist alles implementiert. Der "Done"-Button braucht noch eine Übersetzung, aber ich bin nicht sicher, wie die Übersetzungen genau gehandhabt werden (bin/translation-extract scheint den neuen String nicht zu finden).

**Comment by loechel** [comment]
Übersetzung kümmere ich mich drum, für drag & drop ist neues ticket #29 da.
