### ISSUE TITLE
Widget template: Ausnahme für Kommentare

### ISSUE THREAD

**Issue by reinhardt** [loechel/lmu.contenttypes.blog#2]
Widgets sollen generell im neuen, dreispaltigen Layout angezeigt werden, außer im Kommentar-Formular.

**Comment by reinhardt** [comment]
@loechel, sorry, hätte vielleicht ein Pull Request machen sollen - das Ticket ist fertig und direkt im edit-form branch committed.

**Comment by loechel** [comment]
ist ok, schaue es mir gleich an.

**Comment by loechel** [comment]
Passt
