### ISSUE TITLE
Permission Follow on Blog Entries

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.contenttypes.blog#27]
Wird bei einem Blog-Beitrag ein Workflowstatus welchsel sollen die Bilder und Dateien die in dem Beitrags sind den gleichen workflowstatus erhalten.

**Comment by reinhardt** [comment]
Wäre es dann nicht doch besser, keinen Workflow für Bilder und Dateien fest zu legen? Dann übernehmen sie ja die Berechtigungen vom übergeordneten Blog-Eintrag.

**Comment by loechel** [comment]
Ohne Workflow sind sie immer sichtbar, dann greift Zope2.view,
ohne dass sind sie jetzt immer internal, was dem Internal Draft entspricht und somit gesehen werden sollte. Problematish scheint mir gerade, das Blog und Pinnwand workflow unterschiedlich sind und damit eigentlich intarnet_workflow schlecht passt, zumindest für denn möglich ban fall. PlacefulWorkflows wären eigentlich die richtige Lösung. 

jetzt sind alle immer internal, man muss also die genaue URL kennen. was kein Problem ist.
geht in anderen milestone

**Comment by reinhardt** [comment]
Meinst Du zope.Public?
Ich hab das gestern ausprobiert und die Berechtigungen der Inhalte sind immer schön dem Blog-Eintrag gefolgt. Was genau hattest Du denn im Workflow-Tool eingestellt?
