### ISSUE TITLE
DeletePermission Blog Entry

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.contenttypes.blog#3]
Nutzer sollen ihre eigenen Blog Beiträge löschen können, wenn der Blog Eintrag im Status Privat oder internally_published ist, nicht in gesperrt.

Hierzu soll eine Diealog kommen wie bei der delete_vonfirmation view mit dem Text "Möchten sie diesen "Blog-Beitrag" ${Content-Type} löschen?

**Comment by pbauer** [comment]
collective.deletepermission ist zwar ugly macht aber was es soll.
Hier die drei prs:
https://github.com/loechel/lmu-iuk.buildout/pull/2
https://github.com/loechel/lmu.policy.base/pull/7
https://github.com/loechel/lmu.contenttypes.blog/pull/13

**Comment by pbauer** [comment]
Crap. Ich hab das mit den state-conditions überlesen. Dan muss das wohl doch von Hand gemacht werden.

**Comment by pbauer** [comment]
Oder reicht es wenn der Check (can_delete) of dem button diese conditions überprüft?

**Comment by pbauer** [comment]
@loechel entscheide du.

**Comment by loechel** [comment]
es macht sinn es einfach zu halten und den button nur zu zeigen wenn es gewollt ist, Prinzipiell soll der Owner den Blogbeitrag löschen können, wenn der Beitrag privat oder internally_published ist, aber nicht in banned, dieser Workflowstatus wird im moment aber nicht genutzt. 

Kann also nach hinten geschoben werden.

**Comment by pbauer** [comment]
Dann mergen wir das also und fügen zu `can_delete` noch den check auf die states hinzu.

**Comment by loechel** [comment]
ja, merge das und mach den can_delete check sauber. 

Danke

**Comment by pbauer** [comment]
done
