### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.contenttypes.blog#4]
Die beiden Views frontpage_view und listing_view sollen eine pagination nach der Zurb Foundation Anmutung und Logik haben: http://foundation.zurb.com/docs/components/pagination.html
Basis ist in: https://github.com/loechel/lmu.contenttypes.blog/blob/edit-form/src/lmu/contenttypes/blog/browser/templates/frontpage_view.pt#L160 gesetzt

**Comment by pbauer** [comment]
Für listing_view erledigt: https://github.com/loechel/lmu.contenttypes.blog/pull/16

**Comment by pbauer** [comment]
Dazu gehört noch https://github.com/loechel/lmu.policy.base/commit/16d5bb6cd853741d676fab03ca7f41902b6a3177

**Comment by pbauer** [comment]
Für `FrontPageIncludeView` auch erledigt mit https://github.com/loechel/lmu.contenttypes.blog/commit/1659887e43a95ffbde112bded4097f8c8ff0285c

**Comment by loechel** [comment]
passt, und gemerged
