### ISSUE TITLE
Sortierung für Blog-Beiträge

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.contenttypes.blog#5]
Bisher ist die Sortierung nach dem query feld last_modified gesetzt. soll auf effective gesetzt werden und auch für die paginierung #4 genutzt werden.

Hierzu ist ein Transition Script im Workflow zu machen, der beim ersten Publizieren / wenn das Feld effective leer ist dies mit dem Zeitstempel der Publizierung setzt.

Zusätzlich muss in allen views die Byline geändert werden, das es statt modification date effective date und bei nicht vorhanden das creation date setzt.

**Comment by reinhardt** [comment]
> Hierzu ist ein Transition Script im Workflow zu machen

Ich würde versuchen, das mit dem IPublication Behavior zu machen und mir ein eigenes Script zu sparen - oder ist das explizit nicht erwünscht?

**Comment by loechel** [comment]
IPublication Behavior fügt nur die Felder hinzu, man kann die Felder manuell setzten, es wird aber nicht automatisch gesetzt.

IPublication sollte auch schon in der Definition drin sein, seit meinem letzten commit.

Bitte kurz ansehen, wenn es automatisch gemacht wird, ok, sonst halt ein guard script / transition script das es setzt hinzufügen.

**Comment by reinhardt** [comment]
IPublication ist tatsächlich schon aktiviert und Effective Date wird bereits automatisch gesetzt. Habe die Bylines und die Sortierung angepasst, siehe Pull-Request.

**Comment by reinhardt** [comment]
Notiz an mich: Unveröffentlichte Blog-Einträge
- als unveröffentlicht kennzeichnen
- nach oben sortieren (niedrige Prio)

**Comment by reinhardt** [comment]
Bis auf "nach oben sortieren" müsste alles erledigt sein, siehe #14.

**Comment by loechel** [comment]
wenn das nach oben sorieren nochmal wichtig wird, machen wir ein weiteres ticket auf.
