### ISSUE TITLE
ByLine Anpassen in entry_view, listing_view und frontpage_view --> effective date, Workflowstatus

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.contenttypes.blog#9]
Bitte in allen views die ByLine anpassen, dass wenn effective Date gesetzt, dies in der Byline als Veröffentlichungsdatum erscheint, Fallback, creation date. 
--> Wichtig, das effective bei der Workflow Transtion auf "published" gesetzt wird.

Zusätzlich soll in der Byline im Workflow-Status Privat eine Status Notiz erscheinen, das: "Noch nicht veröffentlicht" + in den listing views ein Link auf die edit form des Beitrages.

**Comment by reinhardt** [comment]
Schon geschehen in #5 bzw. b10b4285c08
